//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.ActivityLogs = new HashSet<ActivityLog>();
        }
    
        public string ActivityID { get; set; }
        public string Name { get; set; }
        public decimal CalorieBurnRate { get; set; }
        public string ImageURL { get; set; }
    
        public virtual ICollection<ActivityLog> ActivityLogs { get; set; }
    }
}
