//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDataGenerator.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CTDatabaseContainer : DbContext
    {
        public CTDatabaseContainer()
            : base("name=CTDatabaseContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<ActivityLog> ActivityLogs1 { get; set; }
        public virtual DbSet<FoodGroup> FoodGroups { get; set; }
        public virtual DbSet<FoodLog> FoodLogs1 { get; set; }
        public virtual DbSet<FoodNutrients> FoodNutrients { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<MetricLog> MetricLogs1 { get; set; }
        public virtual DbSet<Metric> Metrics1 { get; set; }
        public virtual DbSet<Nutrient> Nutrients { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
