//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDataGenerator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetricLog
    {
        public string MetricLogID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string MetricID { get; set; }
        public decimal Value { get; set; }
        public System.DateTime CreationTimestamp { get; set; }
    
        public virtual UserMetric User { get; set; }
        public virtual User Metric { get; set; }
    }
}
