//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDataGenerator.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ActivityLogs = new HashSet<ActivityLog>();
            this.FoodLogs = new HashSet<FoodLog>();
            this.MetricLogs = new HashSet<MetricLog>();
            this.Targets = new HashSet<UserTarget>();
        }
    
        public int UserID { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public sbyte Gender { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public sbyte AdminInt { get; set; }
        public System.DateTime CreationTimestamp { get; set; }
        public int ActivityLevel { get; set; }
        public int PersonalityType { get; set; }
    
        public virtual ICollection<ActivityLog> ActivityLogs { get; set; }
        public virtual ICollection<FoodLog> FoodLogs { get; set; }
        public virtual ICollection<MetricLog> MetricLogs { get; set; }
        public virtual ICollection<UserTarget> Targets { get; set; }
    }
}
