//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calorie_Tracker.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_activity_log
    {
        public string activity_log_id { get; set; }
        public string activity_log_activity_id { get; set; }
        public Nullable<double> activity_log_time { get; set; }
        public Nullable<double> activity_log_distance { get; set; }
        public string activity_log_notes { get; set; }
        public string activity_log_file_url { get; set; }
    
        public virtual tbl_activity tbl_activity { get; set; }
    }
}
