//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.tbl_activity_log = new HashSet<ActivityLog>();
        }
    
        public string activity_id { get; set; }
        public string activity_name { get; set; }
        public decimal activity_calorie_burn_rate { get; set; }
        public string activity_image_url { get; set; }
    
        public virtual ICollection<ActivityLog> tbl_activity_log { get; set; }
    }
}
