//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CalorieEntities : DbContext
    {
        public CalorieEntities()
            : base("name=CalorieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_activity> tbl_activity { get; set; }
        public DbSet<tbl_activity_log> tbl_activity_log { get; set; }
        public DbSet<tbl_food> tbl_food { get; set; }
        public DbSet<tbl_food_group> tbl_food_group { get; set; }
        public DbSet<tbl_food_log> tbl_food_log { get; set; }
        public DbSet<tbl_food_nutrient_log> tbl_food_nutrient_log { get; set; }
        public DbSet<tbl_food_unit> tbl_food_unit { get; set; }
        public DbSet<tbl_metric_log> tbl_metric_log { get; set; }
        public DbSet<tbl_nutrient> tbl_nutrient { get; set; }
        public DbSet<tbl_user> tbl_user { get; set; }
        public DbSet<tbl_user_metric> tbl_user_metric { get; set; }
    }
}
