//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CalorieTrackerEntities : DbContext
    {
        public CalorieTrackerEntities()
            : base("name=CalorieTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<ActivityLog> ActivityLogs { get; set; }
        public virtual DbSet<FoodGroup> FoodGroups { get; set; }
        public virtual DbSet<FoodLog> FoodLogs { get; set; }
        public virtual DbSet<FoodNutritionLogs> FoodNutritionLogs { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<MetricLog> MetricLogs { get; set; }
        public virtual DbSet<Metric> Metrics { get; set; }
        public virtual DbSet<Nutrient> Nutrients { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
