//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_activity> tbl_activity { get; set; }
        public DbSet<ActivityLog> ActivityLogs { get; set; }
        public DbSet<Food> Foods { get; set; }
        public DbSet<FoodGroup> FoodGroups { get; set; }
        public DbSet<FoodLog> FoodLogs { get; set; }
        public DbSet<FoodNutrients> FoodNutrients { get; set; }
        public DbSet<tbl_food_unit> tbl_food_unit { get; set; }
        public DbSet<MetricLog> MetricLogs { get; set; }
        public DbSet<tbl_nutrient> tbl_nutrient { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Metric> Metrics { get; set; }
    }
}
