//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public Food()
        {
            this.FoodNutrients = new HashSet<FoodNutrients>();
            this.FoodLogs = new HashSet<FoodLog>();
        }
    
        public int FoodID { get; set; }
        public int SourceID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int FoodGroupID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ManufacturerName { get; set; }
    
        public virtual FoodGroup FoodGroup { get; set; }
        public virtual ICollection<FoodNutrients> FoodNutrients { get; set; }
        public virtual ICollection<FoodLog> FoodLogs { get; set; }
    }
}
