//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public Food()
        {
            this.tbl_food_log = new HashSet<FoodLog>();
            this.tbl_food_nutrient_log = new HashSet<FoodNutientLog>();
        }
    
        public int food_id { get; set; }
        public int food_source_id { get; set; }
        public Nullable<int> food_parent_id { get; set; }
        public int food_group_id { get; set; }
        public string food_name { get; set; }
        public string food_description { get; set; }
        public string food_manufacture_name { get; set; }
    
        public virtual FoodGroup tbl_food_group { get; set; }
        public virtual ICollection<FoodLog> tbl_food_log { get; set; }
        public virtual ICollection<FoodNutientLog> tbl_food_nutrient_log { get; set; }
    }
}
