//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodLog
    {
        public string FoodLogID { get; set; }
        public int FoodID { get; set; }
        public int UserID { get; set; }
        public decimal Quantity { get; set; }
        public System.DateTime CreationTimestamp { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual User User { get; set; }
    }
}
