//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metric
    {
        public Metric()
        {
            this.tbl_metric_log = new HashSet<MetricLog>();
        }
    
        public string MetricID { get; set; }
        public string user_metric_name { get; set; }
        public int user_metric_type { get; set; }
    
        public virtual ICollection<MetricLog> tbl_metric_log { get; set; }
    }
}
