//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nutrient
    {
        public Nutrient()
        {
            this.tbl_food_nutrient_log = new HashSet<FoodNutientLog>();
        }
    
        public int nutrient_id { get; set; }
        public int nutrient_source_id { get; set; }
        public int nutrient_unit_id { get; set; }
        public string nutrient_name { get; set; }
        public int nutrient_decimal_rounding { get; set; }
    
        public virtual ICollection<FoodNutientLog> tbl_food_nutrient_log { get; set; }
    }
}
