//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NutrientRDA
    {
        public int NutrientRdaID { get; set; }
        public int NutrientID { get; set; }
        public bool Gender { get; set; }
        public int AgeMax { get; set; }
        public int AgeMin { get; set; }
        public decimal Value { get; set; }
        public int UnitType { get; set; }
    
        public virtual Nutrient Nutrient { get; set; }
    }
}
