//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.Design;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;
    using CalorieTracker.Models.Accounts;
    using CalorieTracker.Utilities;

    public partial class tbl_user
    {
        public tbl_user()
        {
            this.tbl_activity_log = new HashSet<tbl_activity_log>();
            this.tbl_food_log = new HashSet<tbl_food_log>();
            this.tbl_user_information = new HashSet<tbl_user_information>();
            this.tbl_user_target = new HashSet<tbl_user_target>();
        }

        public tbl_user(UserContext.RegisterModel newUser)
        {
            this.tbl_activity_log = new HashSet<tbl_activity_log>();
            this.tbl_food_log = new HashSet<tbl_food_log>();
            this.tbl_user_information = new HashSet<tbl_user_information>();
            this.tbl_user_target = new HashSet<tbl_user_target>();
            this.user_id = Guid.NewGuid().ToString();
            PasswordHasher hasher = new PasswordHasher(newUser.Password);
            this.user_password_hash = hasher.PasswordHash;
            this.user_password_salt = hasher.PasswordSalt;
            this.user_creation_date = DateTime.Now.ToString("ddMMyyyyHHmmss");
        }

        [HiddenInput]
        public string user_id { get; set; }
        public string user_email { get; set; }
        public string user_first_name { get; set; }
        public string user_second_name { get; set; }
        public string user_dob { get; set; }
        public string user_password_hash { get; set; }
        public string user_password_salt { get; set; }
        public string user_creation_date { get; set; }
        public string user_profile_image { get; set; }
        public Nullable<sbyte> user_admin { get; set; }
    
        public virtual ICollection<tbl_activity_log> tbl_activity_log { get; set; }
        public virtual ICollection<tbl_food_log> tbl_food_log { get; set; }
        public virtual ICollection<tbl_user_information> tbl_user_information { get; set; }
        public virtual ICollection<tbl_user_target> tbl_user_target { get; set; }
    }
}
