//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_food_nutrient_log
    {
        public int food_nutrient_log_id { get; set; }
        public int food_nutrient_log_food_id { get; set; }
        public int food_nutrient_log_nutrient_id { get; set; }
        public decimal food_nutrient_log_value { get; set; }
    
        public virtual tbl_food tbl_food { get; set; }
        public virtual tbl_nutrient tbl_nutrient { get; set; }
    }
}
