//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Resources;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web.Mvc;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_food_log
    {
        [HiddenInput]
        public string food_log_id { get; set; }
        [HiddenInput]
        public string food_log_user_id { get; set; }
        [HiddenInput]
        [Display(Name = "Food")]
        public string food_log_food_id { get; set; }
        [HiddenInput]
        public string food_log_date { get; set; }
        [Display(Name = "Quantity")]
        public Nullable<double> food_log_quantity { get; set; }
    
        public virtual tbl_food tbl_food { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
