//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        public tbl_user()
        {
            this.tbl_activity_log = new HashSet<tbl_activity_log>();
            this.tbl_food_log = new HashSet<tbl_food_log>();
            this.tbl_user_metric_log = new HashSet<tbl_user_metric_log>();
            this.tbl_user_target = new HashSet<tbl_user_target>();
        }
    
        public string user_id { get; set; }
        public string user_email { get; set; }
        public string user_first_name { get; set; }
        public string user_second_name { get; set; }
        public System.DateTime user_dob { get; set; }
        public sbyte user_gender { get; set; }
        public string user_password_hash { get; set; }
        public string user_password_salt { get; set; }
        public System.DateTime user_creation_timestamp { get; set; }
        public string user_profile_image { get; set; }
        public sbyte user_admin { get; set; }
    
        public virtual ICollection<tbl_activity_log> tbl_activity_log { get; set; }
        public virtual ICollection<tbl_food_log> tbl_food_log { get; set; }
        public virtual ICollection<tbl_user_metric_log> tbl_user_metric_log { get; set; }
        public virtual ICollection<tbl_user_target> tbl_user_target { get; set; }
    }
}
