//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_activity_log
    {
        public string activity_log_id { get; set; }
        public string activity_log_activity_id { get; set; }
        public int activity_log_user_id { get; set; }
        public System.TimeSpan activity_log_duration { get; set; }
        public decimal activity_log_distance { get; set; }
        public string activity_log_title { get; set; }
        public decimal activity_log_accent { get; set; }
        public int activity_log_heart_rate { get; set; }
        public string activity_log_notes { get; set; }
        public string activity_log_file_url { get; set; }
        public System.DateTime activity_log_start_date { get; set; }
    
        public virtual tbl_activity tbl_activity { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
