//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.IO;
    using System.Web.Mvc;
    using CalorieTracker.Validators;
    using CalorieTracker.Models.Accounts;
    using CalorieTracker.Utilities;

    public partial class tbl_food_log
    {
        public tbl_food_log()
        {

        }

        /// <summary>
        /// New Food Log From Log Food View Model
        /// </summary>
        /// <param name="newLog">Food Log View Model</param>
        public tbl_food_log(ViewModels.LogFoodModel newLog)
        {
            this.food_log_id = Guid.NewGuid().ToString();
            this.food_log_user_id = newLog.UserID;
            this.food_log_food_id = newLog.SelectedFood;
            this.food_log_date = DateTime.Now.ToString("ddMMyyyyhhMMss");
            this.food_log_quantity = newLog.Quantity;
        }

        public tbl_food_log(tbl_food newfood)
        {
            this.food_log_id = Guid.NewGuid().ToString();
            //this.food_log_user_id TODO do I need to pass this in or let the controller do it
            this.food_log_food_id = newfood.food_id;
            this.food_log_date = DateTime.Now.ToString("ddMMyyyyhhMMss");
            this.food_log_quantity = newfood.food_quantity;
        }

        [HiddenInput]
        public string food_log_id { get; set; }
        [HiddenInput]
        public string food_log_user_id { get; set; }
        [HiddenInput]
        [Display(Name = "Food")]
        public string food_log_food_id { get; set; }
        [HiddenInput]
        public string food_log_date { get; set; }
        [Display(Name = "Quantity")]
        public Nullable<double> food_log_quantity { get; set; }

        public virtual tbl_food tbl_food { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
