//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_food_group
    {
        public tbl_food_group()
        {
            this.tbl_food = new HashSet<tbl_food>();
        }
    
        public int food_group_id { get; set; }
        public string food_group_name { get; set; }
        public int food_group_source_id { get; set; }
    
        public virtual ICollection<tbl_food> tbl_food { get; set; }
    }
}
