//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_activity_log
    {
        public tbl_activity_log()
        {

        }

        /// <summary>
        /// New Food Log From Log Food View Model
        /// </summary>
        /// <param name="newLog">Food Log View Model</param>
        public tbl_activity_log(ViewModels.LogActivityModel newLog)
        {
            this.activity_log_id = Guid.NewGuid().ToString();
            this.activity_log_activity_id = newLog.SelectedActivity;
            this.activity_log_user_id = newLog.UserID;
            this.activity_log_time = Convert.ToDouble(newLog.Time);
            this.activity_log_distance = Convert.ToDouble(newLog.Distance);
            this.activity_log_notes = newLog.Notes;
            this.activity_log_file_url = newLog.File;
            this.actvitity_log_date = DateTime.Now.ToString("ddMMyyyyHHmmss");
        }
        /// <summary>
        /// Log ID
        /// </summary>
        public string activity_log_id { get; set; }
        /// <summary>
        /// Activity ID
        /// </summary>
        public string activity_log_activity_id { get; set; }
        /// <summary>
        /// User ID
        /// </summary>
        public string activity_log_user_id { get; set; }
        /// <summary>
        /// Activity Time Seconds
        /// </summary>
        public Nullable<double> activity_log_time { get; set; }
        /// <summary>
        /// Activity Time Meters
        /// </summary>
        public Nullable<double> activity_log_distance { get; set; }
        /// <summary>
        /// Activity Notes
        /// </summary>
        public string activity_log_notes { get; set; }
        /// <summary>
        /// Activity GPX/TCX file URL
        /// </summary>
        public string activity_log_file_url { get; set; }
        /// <summary>
        /// Activity Date ddMMyyyyHHmmss
        /// </summary>
        public string actvitity_log_date { get; set; }

        public virtual tbl_activity tbl_activity { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
