//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UserActivityLog = new HashSet<ActivityLog>();
            this.UserFoodLog = new HashSet<FoodLog>();
            this.UserMetricLog = new HashSet<MetricLog>();
        }
    
        public int UserID { get; set; }
        public System.DateTime DOB { get; set; }
        public sbyte Gender { get; set; }
        public string PasswordHash { get; set; }
        public string PasswordSalt { get; set; }
        public sbyte Admin { get; set; }
        public System.DateTime CreationTimestamp { get; set; }
        public int ActivityLevel { get; set; }
        public int PersonalityType { get; set; }
    
        public virtual ICollection<ActivityLog> UserActivityLog { get; set; }
        public virtual ICollection<FoodLog> UserFoodLog { get; set; }
        public virtual ICollection<MetricLog> UserMetricLog { get; set; }
    }
}
