//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Utils.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodNutrient
    {
        public FoodNutrient()
        {
            this.Foods = new HashSet<Food>();
        }
    
        public int FoodNutrientID { get; set; }
        public string FoodID { get; set; }
        public string NutrientID { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<Food> Foods { get; set; }
        public virtual Nutrient Nutrient { get; set; }
    }
}
