//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Utils.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int FoodID { get; set; }
        public string FoodName { get; set; }
        public string FoodDescription { get; set; }
    
        public virtual Log Log { get; set; }
        public virtual FoodNutrient FoodNutrient { get; set; }
    }
}
