//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Utils.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public Log()
        {
            this.Activities = new HashSet<Activity>();
            this.Metrics = new HashSet<Metric>();
            this.Foods = new HashSet<Food>();
        }
    
        public int LogID { get; set; }
        public string UserID { get; set; }
        public string ActivityID { get; set; }
        public string MetricID { get; set; }
        public string FoodID { get; set; }
        public string Quantity { get; set; }
        public string CreationDateTIme { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<Metric> Metrics { get; set; }
        public virtual ICollection<Food> Foods { get; set; }
    }
}
