//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Utils.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metric
    {
        public int MetricID { get; set; }
        public string MetricName { get; set; }
        public string MetricType { get; set; }
    
        public virtual Log Log { get; set; }
    }
}
