//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Utils.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nutrient
    {
        public Nutrient()
        {
            this.FoodNutrients = new HashSet<FoodNutrient>();
        }
    
        public int NutrientID { get; set; }
        public string NutrientName { get; set; }
        public string NutrientValueType { get; set; }
    
        public virtual ICollection<FoodNutrient> FoodNutrients { get; set; }
    }
}
