//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Utils.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Logs = new HashSet<Log>();
        }
    
        public int UserID { get; set; }
        public string DOB { get; set; }
        public string Gender { get; set; }
        public string PasswordHash { get; set; }
        public string Admin { get; set; }
        public string CreationDateTime { get; set; }
    
        public virtual ICollection<Log> Logs { get; set; }
    }
}
