//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalorieTracker.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class calorie_tracker_v1Entities : DbContext
    {
        public calorie_tracker_v1Entities()
            : base("name=calorie_tracker_v1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_activity> tbl_activity { get; set; }
        public DbSet<tbl_activity_log> tbl_activity_log { get; set; }
        public DbSet<tbl_food> tbl_food { get; set; }
        public DbSet<tbl_food_log> tbl_food_log { get; set; }
        public DbSet<tbl_user> tbl_user { get; set; }
        public DbSet<tbl_user_metric> tbl_user_metric { get; set; }
        public DbSet<tbl_user_metric_log> tbl_user_metric_log { get; set; }
        public DbSet<tbl_user_target> tbl_user_target { get; set; }
    }
}
